### PR TITLE
Cleanup theme styles

### PR DESCRIPTION
**Pull request by dfosco**
- Remove `theme.less`
 - Remove theme variables
 - Remove references to theme variables — now using exported theme classes directly in the markup

### CODE REVIEW

**Comment by dfosco** [comment]
@brenoc @tamorim Please review :relieved:

**Comment by brenoc** [comment]
`theme__background-color--secondary`

@dfosco How the other classes will be? Do you have an idea?

**Comment by dfosco** [comment]
@brenoc They are listed in the [theme-exports](https://github.com/vtex-apps/theme/blob/feature/responsive/src/utils/base/theme-exports.less) file in the theme, but here's a general idea: 

```less

.theme {

// ==========  Typography 		==========

  .theme__font-family--main {
    font-family: @modally-main !important;
  }

  .theme__font-family--regular {
    font-family: @modally-regular !important;
  }

// ==========  Font Colors 		==========

  .theme__color--main {
    color: @blue-modally !important;
  }

  .theme__color--secondary {
    color: @green-modally !important;
  }

...

}
```

**Comment by brenoc** [comment]
Oh, nice!

I think there could also be:
- `.theme__h1`, `.theme__h2`, h3, h4, etc.
- `.theme__p`
- `.theme__btn--primary`, `.theme__btn--secondary`

Actually.. those things I listed should be something that the theme should overwrite from Bootstrap, eg:

```css
.btn .btn-primary { 
  background-color: #ff0000;
}

.h1 {
  color: #000;
}

/* and so on */
```

**Comment by dfosco** [comment]
Hmmmm... I like the idea that they should overwrite Bootstrap, but I should look into it more closely before doing it.

I'll leave if for after we finish this first responsive version!

**Comment by dfosco** [comment]
@brenoc Do you think this is good enough to be merged _as is_?

**Comment by tamorim** [comment]
@dfosco theres only the base theme file exporting the css-utils, which the less files already import. I think you can delete the base folder and all references of it from the app :smiley:

**Comment by dfosco** [comment]
@tamorim Do you think so? Seeing that this is an open source app, I like the idea of leaving the scaffolding intact — in case the developer might need to add any global styles to their app, they should put them in `~utils/base/something.less`

**Comment by brenoc** [comment]
@dfosco I agree with @tamorim. Keep it DRY (Don't Repeat Yourself). If a developer needs a global class, he can go back using the `base.less` or the way he prefers. Let's keep our code clean.

**Comment by tamorim** [comment]
@dfosco you can also remove the reference to the css-utils on de less files of the components. Otherwise we are importing the same thing twice

**Comment by dfosco** [comment]
@brenoc Ok, agreed

@tamorim The components need the individual references to `css-utils` to be able to extend the classes inside of their own, such as:

```less
.HeaderSearchButton {
  .css-utils-clean-btn();
}
```

But don't worry, now that the css-utils classes end with `( );` they don't end up compiled unless they are used :smiley:

**Comment by dfosco** [comment]
@brenoc @tamorim Heads up!

PS: This repository is not connected to Slack, can we add it there? I'm not admin here.

**Comment by brenoc** [comment]
@dfosco done! :)

**Comment by brenoc** [comment]
LGTM :+1:

**Comment by dfosco** [comment]
@tamorim Can you take a look? I need to have this merged on master and published to the gallery, otherwise I have to keep this app running on my desktop as well.

**Comment by tamorim** [comment]
@dfosco ok!

**Pull request merged**
